version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Shyp/go-circle
    docker:
      - image: golang:1.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: make test
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
